{% set name = "sasl" %}
{% set version = "0.3.1" %}
{% set sha256 = "f2c8b3ea340f7ee38b7675ee993a529ed157c8d349949f7891a3420a811eabea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/cloudera/python-sasl/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-include-saslutils.h-on-win-for-getpass.patch
    - fix_tp_print.patch

build:
  number: 0
  # no cyrus-sasl on s390x
  skip: True   # [linux and s390x]
  script: python setup.py install --single-version-externally-managed --record record.txt  # [unix]
  ignore_run_exports:
    - cyrus-sasl

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2-patch  # [win]
    - patch     # [not win]
  host:
    - python
    - setuptools
    - cyrus-sasl
    - cython
    - msinttypes    # [win and vc<14]
  run:
    - python
    - six
    - cyrus-sasl

test:
  imports:
    - sasl

about:
  home: https://github.com/cloudera/python-sasl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python wrapper for Cyrus SASL
  description: Python wrapper for Cyrus SASL
  dev_url: https://github.com/cloudera/python-sasl

extra:
  recipe-maintainers:
    - mariusvniekerk
    - wesm
    - martindurant
