travis:
  secure:
    BINSTAR_TOKEN: FPMamJTXJMcC+VTnt525uH9mCwZIeLN8gc4N61m9em835RpTKPG3FC2SUnxPtfHOPq/cT1TFou1x22XUaBwYGGw0UqCkAiaER8ETveouWCF/oB2sEESmimheqjOnOwvvcigUKgV6BIhJLd4z6tZuC8n/3C1NUd35ids1pW4P/JM2dAEVwScGwRglaf7kxol/iOQvLyk3StT5DoV7sVF/mmgB7OFnEpEdq2HCVPcdwV17OXs8QNXF3q9msVHE5Qf5vpSXF1MyZVd9qW4lgtUAxKmAHyszXBYUdCg6JRDw1eHAGvP9jQr0cR5kodNtJ84ks5zf+gSqmtyDs0K1te+kFBCsqDMrY1xiWlVCouUDeQzQ+XeNVRkFZBfWY+UAXdIvP+XYshGjhgTTjskRpgwyfyi7da/ihlin6hsrZUD9z/LSnPkJUIObVvq8lPTTwoM6IE64b2swzUVxcwmOxXAotd/yTX5MiRi4ElODygacKKXZdlJ8WltUPgOPtxuhQhS4esxATxjQM7ggIGiwH0ZLF4bbtznI09sJo0wO/YalYilMEXzT9t4IACbAPajjhOydSEmWdeqCR1MGCjGbUIe3iAosHRU2rCRixGK5uvoEjClCbxwTkE1g80bwiw5S8LY2yuVLmDhGnqun9elG94yxaH6HWT15lp68oolzgoCA2jk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
