travis:
  secure:
    BINSTAR_TOKEN: EYqJaV071wIkE+ipesirNd6GwE/nZ27/+PBqxrdfJpDwDylGLZCdbtLRzTcmPhs4U1hQJ5Ih560zSrdt/SkY1P64TqXHtpc2txP64WMBcA7Mbl2eOSfuKxtaqCaICdi1UYUGlUQJY+PQhJbD+KbR8hsTuj4DkwOODBAEagYYJLeft/KtDWsuTZbO0joekoF2VIjWuG5lidxbFY22xAC9VEYAQ6JBgfg7yC1AmTKCN6nNkiJ7u7uGetNI/r8FhGbf928obTLTiEkhFFDzltTuezOQyb/NepegE+yo5x9giYCAqJIHeV0Sh3dyUDWFTjLIKzwR9rQ0My8s7oOyitELUvqBEmnFOdWJL3RSMqG5UyzBS2uKEYvQbFOkxzTSuiMl8oj19RC2Z7UFm3ao0XchrmNg65va8bQGOdEn3ZA6ZOkCIrKItHfslB3OJBPGpxPsOXtqCX11zETZdMdOVBwuX8LXyPLBSdGACcXYDreXwIQHTzygwG4OJoSUFukfvv44h8YD2TvfeFKVJf17Ong9SaoJ5S2K0gVB3VsH3G/ITbByzeltc9P6GRoofmRJFYYHvWs8zGSwbVPyqE/pKNgk1QzgP80u6RGuUI80D/7PzuU/xoLmyIiO9TJR1NA89bl35EFIAPT7IFnVzv+acj1t1282bqxh+8CpurxAhZdw6Gs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
